---

- name: Dockutil | Get information on items to add
  ansible.builtin.shell: "{{ dockutil_path }} -f '{{ item.name }}'"
  register: dockitems_to_add
  loop: "{{ dockutil.persist|flatten(levels=1) }}"
  changed_when: false
  failed_when: >
    "No such file or directory" in dockitems_to_add.stdout
    or "command not found" in dockitems_to_add.stdout

- name: Dockutil | Debug "add" statement
  ansible.builtin.debug:
    msg: "{{ lookup('template', './templates/add.j2') | replace('\n', '') | trim }}"
  loop_control:
    label: "{{ item.item }}"

- name: Dockutil | Adding items
  ansible.builtin.shell: "{{ lookup('template', './templates/add.j2') | replace('\n', '') | trim }}"
  loop_control:
    label: "{{ item.item }}"
  changed_when: false
