---

- name: Dockutil | Get information on items to add
  ansible.builtin.shell: "{{ dockutil_path }} -f '{{ item.label }}'"
  register: to_map
  loop: "{{ dockutil.dockitems | selectattr('action', 'equalto', 'add') }}"
  changed_when: false
  failed_when: >
    "No such file or directory" in to_map.stdout
    or "command not found" in to_map.stdout
    or "was found in" in to_map.stdout and item.replacing is not defined
  tags:
    - dock-map

- name: Dockutil | Adding items
  ansible.builtin.shell: "{{ lookup('template', './templates/map.j2') | replace('\n', '') | trim }}"
  loop_control:
    label: "{{ item.item }}"
  changed_when: false
  tags:
    - dock-map
