---

- name: Dockutil | Get information on items to add / re-position
  ansible.builtin.shell: "{{ dockutil_path }} -f '{{ item.name }}'"
  register: dockitems_current
  loop: "{{ dockutil.persist|flatten(levels=1) }}"
  changed_when: false
  failed_when: >
    "No such file or directory" in dockitems_current.stdout
    or "command not found" in dockitems_current.stdout
  check_mode: false

- name: Dockutil | Position debug
  ansible.builtin.debug:
    msg: "{{ dockitems_current }}"
