---

- name: Dockutil | Get information on items to remove
  ansible.builtin.shell: "{{ dockutil_path }} --find '{{ item }}'"
  register: dockitems_current
  changed_when: false
  failed_when: >
    "No such file or directory" in dockitems_current.stdout
    or "command not found" in dockitems_current.stdout

- name: Dockutil | remove debug
  ansible.builtin.debug:
    msg: "{{ dockitems_current }}"

- name: Dockutil | Debug "remove" statement
  ansible.builtin.debug:
    msg: "{{ lookup('template', './templates/remove.j2') }} | replace('\n', '') | trim"
  loop_control:
    label: "{{ item.item }}"
  when: not dockutil.remove_all|bool

- name: Dockutil | Remove items only specified in delete list
  ansible.builtin.shell: "{{ lookup('template', './templates/remove.j2') }} | replace('\n', '') | trim"
  loop_control:
    label: "{{ item.item }}"
  when: not dockutil.remove_all|bool
