---

- name: Molecule | Setup | Load default variables
  ansible.builtin.include_vars: "../defaults/main.yml"

# - name: Molecule | Setup | Load scenario variables
#   ansible.builtin.include_vars: defaults/main.yml

- name: Molecule | Setup | Include elliotweiser.osx-command-line-tools
  ansible.builtin.include_role:
    name: elliotweiser.osx-command-line-tools

- name: Molecule | Setup | Include wayofdev.homebrew
  ansible.builtin.include_role:
    name: wayofdev.homebrew

- name: Molecule | Setup | Include wayofdev.dock
  ansible.builtin.include_role:
    name: ansible-role-dock
